# Site settings
title: MSD Visualisation
email: blairni@datacom.co.nz
description: MSD Visualisation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://datacom.github.io/msd-visualisation/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
